/**
 * Regenerate the Supabase Auth email templates from the shared Maple layout.
 *
 *   node scripts/build-email-templates.ts
 *
 * Writes docs/email-templates/<name>.html (Go-template placeholders intact)
 * plus a README listing the subject line for each. Paste each file's HTML and
 * subject into Supabase → Authentication → Emails → Templates.
 */

import { mkdirSync, writeFileSync } from 'node:fs'
import { join } from 'node:path'
import { supabaseTemplates } from '../src/lib/email/templates.ts'

const outDir = join(import.meta.dirname, '..', 'docs', 'email-templates')
mkdirSync(outDir, { recursive: true })

const readme: string[] = [
  '# Supabase Auth email templates',
  '',
  'Generated by `node scripts/build-email-templates.ts` from `src/lib/email/templates.ts`.',
  'Do not hand-edit the HTML files; change the source and rebuild.',
  '',
  'Paste each into Supabase → Authentication → Emails → Templates (subject + body):',
  '',
]

for (const t of supabaseTemplates()) {
  writeFileSync(join(outDir, `${t.file}.html`), t.html, 'utf8')
  readme.push(`- **${t.name}** → \`${t.file}.html\` - subject: \`${t.subject}\``)
  console.log(`wrote ${t.file}.html`)
}

writeFileSync(join(outDir, 'README.md'), readme.join('\n') + '\n', 'utf8')
console.log('wrote README.md')
